### ISSUE TITLE
missing correct version of d2uhelper

### ISSUE THREAD

**Issue by skerbis** [TobiasKrais/d2u_courses#1]
there is no d2u_helper 1.4.7 in the Installer. 
![bildschirmfoto 2018-08-09 um 12 15 32](https://user-images.githubusercontent.com/791247/43893037-f32aef12-9bcd-11e8-814b-70286f887535.png)

**Comment by TobiasKrais** [comment]
Oh, sorry. Hatte vergessen den "Online" Haken beim Upload der Version 1.4.7 von d2u_helper zu setzen. So was ist mir auch noch nie passiert. Jetzt sollte es gehen.
