### ISSUE TITLE
Anlage einer Terminkategorie führt zu Whoops

### ISSUE THREAD

**Issue by skerbis** [TobiasKrais/d2u_courses#2]
PHP 8.1

**rex_sql_exception:** Error while executing statement "SELECT * FROM rex_d2u_courses_schedule_categories WHERE schedule_category_id = " using params []! SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1
**File:** redaxo/src/core/lib/sql/sql.php
**Line:** 424

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                                                                | Line     |
| -------------------------------------------- | ----------------------------------------------------------------------------------- | -------- |
| rex_sql->execute                             | redaxo/src/core/lib/sql/sql.php                                                     | 467      |
| rex_sql->setQuery                            | redaxo/src/addons/d2u_courses/plugins/schedule_categories/lib/schedule_category.php | 64       |
| D2U_Courses\ScheduleCategory->__construct    | redaxo/src/addons/d2u_courses/plugins/schedule_categories/lib/schedule_category.php | 329      |
| D2U_Courses\ScheduleCategory->save           | redaxo/src/addons/d2u_courses/plugins/schedule_categories/pages/index.php           | 30       |
| require                                      | redaxo/src/core/lib/packages/package.php                                            | 233      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php                                               | 497      |
| rex_be_controller::{closure}                 | redaxo/src/core/lib/util/timer.php                                                  | 57       |
| rex_timer::measure                           | redaxo/src/core/lib/be/controller.php                                               | 498      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php                                               | 447      |
| rex_be_controller::includeCurrentPageSubPath | redaxo/src/addons/d2u_courses/pages/index.php                                       | 4        |
| require                                      | redaxo/src/core/lib/packages/package.php                                            | 233      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php                                               | 497      |
| rex_be_controller::{closure}                 | redaxo/src/core/lib/util/timer.php                                                  | 57       |
| rex_timer::measure                           | redaxo/src/core/lib/be/controller.php                                               | 498      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php                                               | 430      |
| rex_be_controller::includeCurrentPage        | redaxo/src/core/backend.php                                                         | 241      |
| require                                      | redaxo/src/core/boot.php                                                            | 143      |
| require                                      | redaxo/index.php                                                                    | 9        |

</details>

**Comment by TobiasKrais** [comment]
Ja, hab ich letzte Woche behoben. Bitte die Git Version ziehen und nochmals versuchen.
