### ISSUE TITLE
Addon Anleitung

### ISSUE THREAD

**Issue by gregor72** [TobiasKrais/d2u_courses#3]
Hallo,
gibt es eine Anleitung zu diesen Addon wie man es richtig einrichtet?
Das Addon ist cool aber man tutu sich schon etwas schwierig das ganze zum laufen zu bringen.
VG Gregor

**Comment by TobiasKrais** [comment]
Oh ja, das sollte ich unbedingt machen. Nicht nur in diesem Projekt fehlt die README.md. Wird gemacht, dauert aber noch ein wenig...

**Comment by gregor72** [comment]
ok, kein Problem, die liebe Zeit das kenn ich.
Hätte da aber 1-2 Frage weil ich gerade da nicht weiter komme, vielleicht kannst Du mir 1-2 Tipps / Infos geben:

1. Wenn ich eine Veranstaltung anlege da kann ich unten ein Redaxo Artikel verknüpfen, das wäre z.B. ein Artikel mit weiteren Infos, oder ist das die Seite wo die Inhalte aus der Veranstaltung angezeigt werden?

2. Dann wenn ich Das Modul: "26-3 D2U Veranstaltungen - Ausgabe Veranstaltungen einer Kategorie" verwende und es richtig verstehe wie das ganze funktioniert. Dann durch die Nutzung von dem URL Addon werden URLs generiert und bei Aufruf dieser URLs sollten dann die hinterlegten Infos / Kursdaten aus deine D2U Veranstaltungen Addon ausgegeben und angezeigt werden. Die Seiten werden automatisch generiert, ist das so richtig? 


Mein Problem im Augenblick ist dass wenn ich so eine URL aufrufe, die URL wird im Browser richtig angezeigt aber ich bekomme ich die 404 Seite zusehen. Kannst du mir vielleicht sagen wo mein Problem liegt, muss ich irgend ein Code in das Template einbauen, kann es damit zusammen hängen das ich dem Code von Warenkorb noch nicht eingebaut habe? 

VG Gregor

**Comment by TobiasKrais** [comment]
Gute Fragen. Zu 
1. Die Infos zum Kurs sollten im Kurs platziert werden. Der Artikellink bezieht sich auf Zusatzinformationen oder Hintergrundartikel. Ich werde die Beschreibung in "Redaxo Zusatzartikel" umbenennen.
2. Ja, genau. Dieses Modul brauchst du nur, wenn du außerhalb des Moduls 26-1 die Kategorien angezeigt haben willst und auf die Kurse verlinken möchtest.
3.  Hast du  in den Einstellungen des Addons die Artikel korrekt gesetzt? Und in YRewrite ist die .htaccess korrekt gesetzt?

**Comment by gregor72** [comment]
Hallo Tobias,
habe mir das ganze gerade angeschaut, die YRewrite richtig eingestellt , alles andere müsste auch glaube passen. 
Jetzt werden die URLs richtig angezeigt, und mein Problem das ich immer auf der 404 Seite gelandet bin habe ich nicht mehr. 

Ich habe aber ein anderes Problem wenn ich ein Kurs anklicke um die Kursdetails ansehen will.
Hängt mit kufer XML sync / schreiben. ich habe da nichts eingerichtet weil ich das nicht brauchen,
kannst Du an hand von diesen Code erkennen wieso es bei mir nicht geht? sind es die Verzeichnis Zugriffsrechte?
 
Banke und VG Gregor

![Bildschirm­foto 2023-05-04 um 22 56 23](https://user-images.githubusercontent.com/49267482/236327315-b0e5d21e-21a7-496e-ba83-66435d7b66de.png)


`**ParseError:** syntax error, unexpected identifier "o777", expecting ")"
**File:** redaxo/src/addons/d2u_courses/lib/cart.php
**Line:** 524

<details>
<summary>Stacktrace</summary>

| Function                                           | File                                                                       | Line     |
| -------------------------------------------------- | -------------------------------------------------------------------------- | -------- |
| rex_autoload::autoload                             | rex:///module/24/output                                                    | 5        |
| require                                            | redaxo/src/addons/structure/plugins/content/lib/article_content_base.php   | 491      |
| rex_article_content_base->{closure}                | redaxo/src/addons/structure/plugins/content/lib/article_content_base.php   | 493      |
| rex_article_content_base->getStreamOutput          | redaxo/src/addons/structure/plugins/content/lib/article_content_editor.php | 272      |
| rex_article_content_editor->getWrappedModuleOutput | redaxo/src/addons/structure/plugins/content/lib/article_content_editor.php | 85       |
| rex_article_content_editor->outputSlice            | redaxo/src/addons/structure/plugins/content/lib/article_content_base.php   | 695      |
| rex_article_content_base->renderSlices             | redaxo/src/addons/structure/plugins/content/lib/article_content_base.php   | 406      |
| rex_article_content_base->getArticle               | redaxo/src/addons/structure/plugins/content/lib/article_content.php        | 106      |
| rex_article_content->getArticle                    | redaxo/src/addons/structure/plugins/content/pages/content.edit.php         | 35       |
| require                                            | redaxo/src/core/lib/packages/package.php                                   | 280      |
| rex_package->includeFile                           | redaxo/src/core/lib/be/controller.php                                      | 481      |
| rex_be_controller::{closure}                       | redaxo/src/core/lib/util/timer.php                                         | 63       |
| rex_timer::measure                                 | redaxo/src/core/lib/be/controller.php                                      | 482      |
| rex_be_controller::includePath                     | redaxo/src/core/lib/be/controller.php                                      | 431      |
| rex_be_controller::includeCurrentPageSubPath       | redaxo/src/addons/structure/plugins/content/pages/content.php              | 432      |
| require                                            | redaxo/src/core/lib/packages/package.php                                   | 280      |
| rex_package->includeFile                           | redaxo/src/core/lib/be/controller.php                                      | 481      |
| rex_be_controller::{closure}                       | redaxo/src/core/lib/util/timer.php                                         | 63       |
| rex_timer::measure                                 | redaxo/src/core/lib/be/controller.php                                      | 482      |
| rex_be_controller::includePath                     | redaxo/src/core/lib/be/controller.php                                      | 414      |
| rex_be_controller::includeCurrentPage              | redaxo/src/core/backend.php                                                | 239      |
| require                                            | redaxo/src/core/boot.php                                                   | 143      |
| require                                            | redaxo/index.php                                                           | 9        |

</details>
<details>
<summary>System report (REDAXO 5.14.2, PHP 8.0.27, MySQL 5.7.41)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.14.2     |


| PHP           |            |
| ------------: | :--------- |
|       Version | 8.0.27     |
|       OPcache | yes        |
|        Xdebug | no         |


| Database      |              |
| ------------: | :----------- |
|       Version | MySQL 5.7.41 |
| Character set | utf8mb4      |


| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |


| Request       |             |
| ------------: | :---------- |
|       Browser | Safari/16.3 |
|      Protocol | HTTP/1.1    |
|         HTTPS | yes         |


| Packages                        |            |
| ------------------------------: | :--------- |
|                          backup | 2.8.2      |
|                        be_style | 3.1.1      |
|             be_style/customizer | 3.1.0      |
|                 be_style/redaxo | 3.1.1      |
|                         cronjob | 2.9.0      |
|                     d2u_courses | 3.3.0      |
|           d2u_courses/locations | 3.3.0      |
| d2u_courses/schedule_categories | 3.3.0      |
|       d2u_courses/target_groups | 3.3.0      |
|                      d2u_helper | 1.10.3     |
|   d2u_helper/translation_helper | 1.10.3     |
|                         install | 2.10.0     |
|                   media_manager | 2.13.2     |
|                       mediapool | 2.12.0     |
|                        metainfo | 2.9.0      |
|                       phpmailer | 2.11.2     |
|                         project | dev        |
|                        redactor | 2.3.0      |
|                           sprog | 1.5.1      |
|                       structure | 2.14.2     |
|               structure/content | 2.14.2     |
|                             url | 2.1.0      |
|                           users | 2.9.1      |
|                           yform | 4.0.4      |
|                     yform/email | 4.0.4      |
|                   yform/manager | 4.0.4      |
|                        yrewrite | 2.9.1      |

</details>`

**Comment by TobiasKrais** [comment]
Danke für die Fehlermeldung. PHP < 8.1 ist die Ursache. Der Fehler wird hier behoben: https://github.com/TobiasKrais/d2u_courses/commit/ed945155f14a650ca2019e7e298fdad32e6c4d2e

**Comment by gregor72** [comment]
Perfekt, Viele Dank. 
Ich werde es nachher Probieren.
